### ISSUE TITLE
Integer overflow

### ISSUE THREAD

**Issue by simplylizz** [rickb777/date#15]
> This package introduces a light-weight Date type that is storage-efficient and convenient for calendrical calculations and date parsing and formatting (including years outside the [0,9999] interval).

This statement from the docs is misleading. Attempt to parse any date with numbers greater than `(1 << 15) / 10 - 1` (e.g. `P3276Y`) will result into the integer overflow error. In order to support such dates you need either to split decimal part into a separate field(s) or use at least `int32` to store values.

Just in case, if you're interested, I've implemented int32 approach in the fork:
https://github.com/simplylizz/date

**Comment by rickb777** [comment]
It was a deliberate design decision to limit the range of period fields to +- 2^15/10 (approx) by using `int16`. I have also been exploring moving the fraction to its own field, which increases the range to the full `int16` but makes the logic much more complex, alas.

You might have noticed that there is also an unexported period64 with `int64` fields that is used internally for intermediate steps in calculations.

**Comment by rickb777** [comment]
I have decided to re-implement period rather than continue to patch it. The new period package will be https://github.com/rickb777/period. This will incorporate your remarks indirectly - it uses int64 instead of int16.

**Comment by simplylizz** [comment]
Thanks for the update. Will notify guys from my previous job. :)

**Comment by rickb777** [comment]
Closing this issue now that the [new period module](https://github.com/rickb777/period) is available.
