### ISSUE TITLE
Support for combination of positive and negative durations in period.Parse

### ISSUE THREAD

**Issue by ketilt** [rickb777/date#20]
This appears to be a feature of ISO-8601 which is supported in some frameworks, like PostgreSQL. If it was also supported in this package, it would make interaction with such frameworks easier.

I have not bought access to ISO-8601, so my reference is only second-hand from the PostgreSQL community (https://www.postgresql.org/message-id/9q0ftb37dv7.fsf%40gmx.us):

> | EXAMPLE 5 'P-3M-3DT1HSM', duration of three months and three days in the reverse direction, with one hour
> | and five minutes in the original direction.

Such strings are produced by PostgreSQL's interval type when intervaltype set to iso_8601. Managing this type is already a challenge in golang, so it would be all the more useful to be able to parse them using this package.

Test case:
```
p1, err := period.Parse("P1DT-18H")
if err != nil {
	fmt.Fatalln(err)
}
```
Output:
```
P1DT-18H: expected a number but found '-'
```

It appears that negative and positive durations can already be added and handled (and printed) correctly. My workaround will be to try and split up the parts of the string and modify, parse and add them individually. It would be wonderful if period.Parse could handle this in future versions.

**Comment by rickb777** [comment]
Closing this issue now that the [new period module](https://github.com/rickb777/period) is available.
