### ISSUE TITLE
Calling period.AddTo(time) in a loop stops and repeats

### ISSUE THREAD

**Issue by zeroallox** [rickb777/date#22]
Greetings,

I'm experiencing an issue where when i call period.AddTo in a loop it reaches a certain date and then repeats.

Not sure how else to describe it.

Here is a code example:
https://gist.github.com/zeroallox/1fb3812ec6572c39cad670d59eacd486

When i run this, dates will print in sequence correctly up until `2020-11-01 01:00:00 -0500 EST` and then start repeating.

Thanks for your time and this wonderful library.

🍍

**Comment by rickb777** [comment]
This may be due to a bug in time.Time AddDate method. It's not a problem for `Europe/London` but is for `America/New York`.

I found a workaround, which is also slightly faster.

**Comment by rickb777** [comment]
The example here https://go.dev/play/p/RJLuUp8YeUW illustrates the issue more directly. I still haven't yet found the cause though.

**Comment by rickb777** [comment]
The problem arises when calling `t.AddDate(0, 0, 0).Add(d)` but not with `t.Add(d)`. 
See https://go.dev/play/p/KTOOGgk-_n9

This doesn't involve the `period` api but I will add my workaround so that this stops being a problem.
