### ISSUE TITLE
empty string unmarshals as zero-value date rather than erroring

### ISSUE THREAD

**Issue by danny-goldberg-transcarent** [rickb777/date#25]
Hi @rickb777 , we noticed that the date package unmarshals an empty string to the date zero value (epoch in v1, `0001-01-01` in v2).

Is this intentional behavior? Would you welcome a change request to make empty string unmarshal fail?

proof in:
- https://github.com/rickb777/date/pull/24

**Comment by rickb777** [comment]
I deliberately added that behaviour in December 2021, although I've forgotten why.
Hmmm

**Comment by rickb777** [comment]
Oh I remembered - it's so that the JSON 'omitempty' tag can work.

**Comment by rickb777** [comment]
It seems that the JSON processor handles the blank string automatically and it was an error to code for this.

Please review this commit https://github.com/rickb777/date/commit/79350eb05ce669566f3c96e8cb51ea0875ce7fc3
and let me know whether it addresses your issue.

**Comment by danny-goldberg-transcarent** [comment]
> It seems that the JSON processor handles the blank string automatically and it was an error to code for this.
> 
> Please review this commit [79350eb](https://github.com/rickb777/date/commit/79350eb05ce669566f3c96e8cb51ea0875ce7fc3) and let me know whether it addresses your issue.

thanks so much @rickb777 - that's exactly what I was hoping for :)
