### ISSUE TITLE
Incorrect calculation

### ISSUE THREAD

**Issue by mihaiav** [rickb777/date#5]
It seems the duration is incorrectly calculated/formatted. Is this a known bug/behaviour?

```
package main

import (
	"fmt"
	"github.com/rickb777/date/period"
	"time"
)

func main() {
	const e = "PT30M67.6S"
	d := (time.Minute * 30) + (time.Second * 67) + (time.Millisecond * 600)
	p, _ := period.NewOf(d)
	if p.String() != e {
		fmt.Printf("expected %s, received %s", e, p)
	}
}

```

`expected PT30M67.6S, received PT31M7.6S`

[Play(play.golang.org)](https://play.golang.org/p/fWTOd8lqN40)

**Comment by rickb777** [comment]
This is demonstrating correct behaviour because "PT30M67.6S" is actually "PT31M7.6S", because of the 60-second carry into the minutes. The Period implementation stores the parsed value, not the original string, so it is unable to reconstruct the original non-normalised value.
